### ISSUE TITLE
Clarify Readme for GitLab Runner Token

### ISSUE THREAD

**Issue by charliesolomon** [oprudkyi/openshift-templates#2]
The Readme contains this line:

GitLab Runner Token : one from /etc/gitlab-runner/config.toml

I can't figure out how to retrieve that token.  I haven't installed gitlab-runner yet (at this point in the instructions, I've only created the OpenShift template.)

Can you clarify this step please?

**Comment by oprudkyi** [comment]
Hi, you need to install gitlab runner locally and get that value from config.toml (it's not the one from gitlab site but 'secret' one generated after install/config)

**Comment by charliesolomon** [comment]
> install gitlab runner locally
What do you mean by "locally"?  On any machine?  I'm using this yaml template on an OpenShift cluster of servers.

**Comment by oprudkyi** [comment]
yes, you install and register runner via any way described at the http://docs.gitlab.com/runner/register/
and then check generated config.toml for real token

**Comment by oprudkyi** [comment]
also there is described registration via kubernetes http://blog.lwolf.org/post/how-to-easily-deploy-gitlab-on-kubernetes/

**Comment by charliesolomon** [comment]
Thanks.  I ended up running the "gitlab-runner register" command from inside the running container on OpenShift.
